### PR TITLE
A Visual Studio 2019 compatible version

### PR DESCRIPTION
**Pull request by denisabt**
Hey, I love your extension often, so I thought I'd give it a try. I hope this is the correct way/pull request to let you know about the change and if wanted, merge it into your repo ?

### CODE REVIEW

**Comment by tanathos** [comment]
Hey, sorry for the late response.
I've some problems getting your code to work, there's something strange on the ClippyVSPackage.csproj file.
It looks like you didn't remove the packages.config references for the Analyzers, maybe locally to you still works because you have the ..\packages\ folder, but I'm unable to restore them as the packages.config file is gone (as it should).
If you can fix it I'll be happy to merge!

**Comment by denisabt** [comment]
Hey, no worries about the late response. You are right, something if not yet right with the PR, I will have a look and update, thanks!

**Comment by denisabt** [comment]
This should now be working and compilable. Analyzers are removed, a few fixes applied and all unneeded references . Compilation tested by downloading Source Code as ZIP file and running compilation.

**Comment by tanathos** [comment]
Thanks man, works perfectly now.
Is it ok for you if I update the VSIX here? https://marketplace.visualstudio.com/items?itemName=ErosFratini.ClippyVS

**Comment by denisabt** [comment]
Nice one, thanks for testing, merging so quickly. My first merged public PR, awesome ! 
Yes, please update the VSIX, so that interested VS users can get the latest version.
I will soon send another PR most likely, as I have completed, over a past weekend, adding Merlin as Assistant. Will do some cleanups and Options fixes for that and then send it.

**Pull request merged**
